@startuml


package "Game" #lightgrey {
  class Dice
  class DM
  class Dungeon
  package Entities #7db87d{
    package Classes #palegreen{
        abstract class CharacterClass
        class Rogue extends CharacterClass
        class Cleric extends CharacterClass
        class Warrior extends CharacterClass
        class Wizard extends CharacterClass
    }
    package Races #palegreen{
        abstract class Races
        class Human extends Races
        class Elf extends Races
        class Dwarf extends Races
        class Halfling extends Races
    }
    class Character {
        - String _name
        - Race _race;
        - CharacterClass _class;
        - Statistics _stats;
        - List<Equipment> _equipment;
        - Weapon _equippedWeapon;
        - Armor _equippedArmor;
    }
    class Monster
    class Statistics {
        - int _hp
        - int _strength
        - int _dexterity;
        - int _speed;
        - int _initiative;
    }
  }
  package Equipment #ca82f5{
    abstract class Equipment
    abstract class Weapon extends Equipment
    abstract class Armor extends Equipment
    class MeleeWeapon extends Weapon
    class RangedWeapon extends Weapon
    class WarMeleeWeapon extends Weapon
    class LightArmor extends Armor
    class HeavyArmor extends Armor




  }
 }

@enduml