@startuml

left to right direction
skinparam classfontStyle bold
skinparam shadowing true

skinparam linetype ortho
skinparam defaultFontName "Century Gothic"

skinparam roundcorner 15


class Main #Bisque {
    + main(args : String[]) : void
}


package "game" <<frame>> #b3b3b3  {

package utils #palegreen{
    class Utils #Bisque {
        + {static} RESET : String
        + {static} RED : String
        + {static} GREEN : String
        + {static} BLUE : String
        + {static} PURPLE : String
        + {static} YELLOW : String
        + {static} WHITE_BG : String
        + {static} random : Random
        + {static} scanner : Scanner
        + {static} roll(num : Integer, sides : Integer) : Integer
        + {static} parsePosition(position : String) : int[]
        + {static} askValidInt(prompt : String, min : Integer, max : Integer) : Integer
        + {static} askValidPosition(prompt : String, Dungeon D) : Integer[]
    }

    class Repo  #Bisque {
        + <<create>> Repo()
        + addEquipment(equipment : Equipment)
        + removeEquipment(equipment : Equipment)
        + getEquipmentByName(name : String) : Equipment
        + getEquipments() : List<Equipment>
        + toString() : String
    }

    class Display #Bisque {
        + {static} display(stuff : String)
        + {static} displayError(stuff : String)
        + {static} displayLore(stuff : String)
        + {static} displaySuccess(stuff : String)
        + {static} displayInfo(dm : DM)
        + {static} displayEntityInfo(entity : Entity)
        + {static} displayLao(dungeon : Dungeon)
        + {static} displayClear()
        + {static} displayActionMenu(currentEntity : Entity, actions : Integer)
        + {static} displayDmActions()
        + {static} displaySpellsMenu(entities : Entity)
    }
}


  'End of utils package



  class Positions #Bisque {
    - _obstacles : List<int>
    + <<create>> Positions()

    + addEntity (entity : Entity, position : int[])
    + addEquipment (equipment : Equipment, position : int[])
    + addObstacle (position : int[])
    + removeEntity (entity : Entity)
    + removeEquipment (equipment : Equipment)

    + distanceBetween(entity1 : Entity, targetPosition : int[]) : Integer

    + getEntitiesPosition() : HashMap<Entity, int[]>
    + getEquipmentPosition() : HashMap<Equipment, int[]>
    + getObstacles() : List<int>

  }

  class DM #Bisque {
    - _turn : Integer
    - _winCondition : Boolean
    + <<create>> DM()

    + createCharacters()
    + createMonsters()
    + createEquipment()
    + createDungeon(number : Integer)
    + setDungeon()
    + createGame()
    + nextDungeon()
    + turn()
    + play()
    + gameEnd()

    + allPlayersDead() : Boolean
    + allMonstersDead() : Boolean

    + getEntitiesSortedByInitiative() : List<Entity>
    + getTurn() : Integer
    + getCurrentEntity() : Entity
    + getDungeonNumber() : Integer

    + toString() : String
  }
  class Dungeon #Bisque {
    - _map : String[][]
    - _height : Integer
    - _width : Integer
    - _number : Integer
    + <<create>> Dungeon(height : Integer, width : Integer, number : Integer)

    + IsValidPosition(x : Integer, y : Integer)

    + addEntity(x : Integer, y : Integer, entity : Entity)
    + addEquipment(x : Integer, y : Integer, equipment : Equipment)
    + addObstacle(x : Integer, y : Integer)
    + randomSetEntity(entity : List<Entity>)
    + randomSetEquipment(equipment : List<Equipment>)
    + randomSetObstacle()

    - setObstacles()
    - setEntities()
    - setEquipment()
    + updateMap()
    + displayGrid()

    + attack(attacker : Entity, pos : String)
    + equip (entity : Entity, equipment : Equipment)
    + move(entity : Entity, position : String)
    + pickUp(entity : Entity, position : String)
    + comment(entity : Entity, comment : String)
    + castSpell(entity : Entity)

    + moveEntity(entity : Entity, x : Integer, y : Integer)
    + hurtEntity(entity : Entity, dices : Integer, sides : Integer)

    + switchEntities(entity1 : Entity, entity2 : Entity)

    + getDungeonNumber() : Integer
    + getEntityAtPosition(x : Integer, y : Integer) : Entity
    + getEquipmentAtPosition(x : Integer, y : Integer) : Equipment
    + getNumber() : Integer

    + toString() : String
  }

  package entities #7db87d{

  abstract class Entity <<abstract>> #Bisque {
          - _name : String
          - _pseudo : String
          - _maxHp : Integer
          # <<create>> Entity(Name : String)

          + removeHp(hp : Integer)
          + isPlayer : Boolean
          + isMonster : Boolean
          + isAlive() : Boolean
          + canAttack : Boolean
          + {abstract} equipWeapon(weapon : Equipment)
          + {abstract} equipArmor(armor : Equipment)
          + {abstract} displayInventory()
          + setEquippedWeapon(weapon : Weapon)
          + setEquippedArmor(armor : Armor)
          + setHp(hp : Integer)
          + setMaxHp(maxHp : Integer)
          + setPseudo(pseudo : String)

          + getName() : String
          + getPseudo() : String
          + getStats() : Statistics
          + getInitiative() : Integer
          + getMaxHp() : Integer
          + getHp() : Integer
          + getAC() : Integer
          + getEquippedWeapon() : Weapon
          + getEquippedArmor() : Armor
          + getColor() : String

          + {abstract} getInfo() : String
          + {abstract} getInventory() : List<Equipment>
          + {abstract} toString() : String
      }

      class Monster #Bisque extends Entity  {
          - _number : Integer
          - _AC : Integer
          + <<create>> Monster(species : String, number : Integer,
           weapon : Weapon, AC : Integer)

          + isMonster() : Boolean

          + getColor() : String
          + getInfo() : String
          + getAC() : Integer
          + toString() : String

      }

      class Character #Bisque extends Entity   {
          + <<create>> Character(name : String, race : Race,
           characterClass : CharacterClass)

          + isPlayer() : Boolean
          + isCleric() : Boolean
          + isWizard() : Boolean

          + displayInventory() : String
          + addToInventory(equipment : Equipment)

          + toString() : String
      }
      class Statistics #Bisque {
          -_hp :  Integer
          -_strength :  Integer
          -_dexterity :  Integer
          -_speed :  Integer
          -_initiative : Integer

          + <<create>> Statistics()
          + <<create>> Statistics(hp : Integer, strength : Integer, dexterity : Integer, speed : Integer, initiative : Integer)

          + addStatistics(s : statistics)
          + removeStatistics(s : statistics)

          + getHp() : Integer
          + getStrength() : Integer
          + getDexterity() : Integer
          + getSpeed() : Integer
          + getInitiative() : Integer

          + toString() : String

      }
    package classes #palegreen{
        abstract class CharacterClass <<abstract>> #Bisque {
        - _name : String
        # <<create>> CharacterClass(name : String , bonusStats : Statistics,
         startingEquipment : Equipment.Equipment[*]))

        + getStartingEquipment() : Equipment.Equipment[*]
        + getBonusStats() : Statistics
        + getName() : String

        + toString() : String
        }
        class Rogue extends CharacterClass {
        + <<create>> Rogue()
        + toString() : String
        }
        class Cleric extends CharacterClass {
        + <<create>> Cleric()
        + toString() : String
        }
        class Warrior extends CharacterClass {
        + <<create>> Warrior()
        + toString() : String
        }
        class Wizard extends CharacterClass {
        + <<create>> Wizard()
        + toString() : String
        }
    }
    package races #palegreen{
        abstract class Race <<abstract>> #Bisque {
        - _name : String
        # <<create>> Race(name : String , bonusStats : Statistics)

        + getBonusStats() : Statistics
        + getName() : String

        + toString() : String
        }
        class Human extends Race {
        + <<create>> Human()
        + toString() : String
        }
        class Elf extends Race {
        + <<create>> Elf()
        + toString() : String
        }
        class Dwarf extends Race {
        + <<create>> Dwarf()
        + toString() : String
        }
        class Halfling extends Race {
        + <<create>> Halfling()
        + toString() : String
        }
    }



  }


  package items #ca82f5 {
    abstract class Equipment <<abstract>>  #Bisque {
    - _name : String
    # <<create>> Equipment(name : String)

    + isArmor() : Boolean
    + isWeapon() : Boolean

    + getAC() : Integer
    + getName() : String

    + toString() : String
    }

    abstract class Weapon <<abstract>> #Bisque extends Equipment  {
    - _range : Integer
    - _damageroll : Integer
    - _dicenumb : Integer
    - _bonus : Integer
    # <<create>> Weapon(name : String, range : Integer,
     damageroll : Integer, bonusStat : Statistics)

     + addBonus(bonus : Integer)
     + damage() : Integer

     + getRange() : Integer
     + getDamage() : String
     + getBonus() : Integer

     + toString() : String

    }
    abstract class Armor <<abstract>> #Bisque extends Equipment{
    - _AC : Integer
    # <<create>> Armor(name : String, AC : Integer,
     bonusStat : Statistics)

     + isArmor() : Boolean

     + getAC() : Integer

     + toString() : String
    }

    class MeleeWeapon extends Weapon {
    + <<create>> MeleeWeapon( _name : String,
    _range : Integer, _damageroll : Integer)
    + toString() : String
    }
    class RangedWeapon extends Weapon {
    + <<create>> RangedWeapon(_name : String,
    _range : Integer, _damageroll : Integer)
    + toString() : String
    }
    class WarMeleeWeapon extends Weapon {
    + <<create>> WarMeleeWeapon(_name : String,
     _range : Integer, _damageroll : Integer)
    + toString() : String
    }
    class LightArmor extends Armor {
    + <<create>> LightArmor(_name : String,
     _AC : Integer)
    + toString() : String
    }
    class HeavyArmor extends Armor {
    + <<create>> HeavyArmor(_name : String,
     _AC : Integer)
    + toString() : String
    }
  }

package spells #ba20d5 {
    abstract class Spell <<abstract>>  #Bisque {
        - _name : String
        # <<create>> Spell(name : String)

        + {abstract} cast(target : Entity)
        + {abstract} cast(target : Equipment)
        + {abstract} cast(target1 : Entity, target2 : Entity, d : Dungeon)

        + getName() : String

        + toString() : String
    }
    class Heal extends Spell {
        + <<create>> HealingSpell(name : String)
        + cast(target : Entity)
    }
    class BoogieWoogie extends Spell {
        + <<create>> BoogieWoogie(name : String)
        + cast(target1 : Entity, target2 : Entity, d : Dungeon)
    }
    class MagicWeapon extends Spell {
        + <<create>> MagicWeapon(name : String)
        + cast(target : Equipment)
        + selectEquipmentToEnchant(char : Character)
    }







}


'Links


  utils.Repo "1"  o--> "-_repo[*]" Equipment : "> has"


  Positions "1"  o..* "_entitiesPosition" entities.Entity : "> uses"
  Positions "1"  o..* "_equipmentPosition" Equipment : "> uses"


  DM "1"  o--> "-_dungeon" Dungeon : "> plays on"
  DM "1"  o--> "-_equipmentList" Equipment : "> has"
  DM "1"  o--> "-_entitiesSortedByInitiative" Entity : "> has"
  DM "1"  o--> "-_equipmentRepo" utils.Repo : "> has"
  DM "1"  o--> "-_currentEntity" Entity : "> has"

  Dungeon "1" *--> "-_positions" Positions : "> has"

  entities.Entity "1"  o--> "-_equippedWeapon" items.Weapon : "> uses"
  entities.Entity "1"  o--> "-_equippedArmor" items.Armor : "> wears"
  entities.Entity "1"  *--> "-_stats" entities.Statistics : "> has"


  entities.Character "1"  *--> "-_class" entities.classes.CharacterClass : "> is"
  entities.Character "1"  *--> "-_race" entities.races.Race : "> is"
  entities.Character "1"  o--> "-_inventory" items.Equipment : "> has"
  entities.Character "1"  o--> "-_spells" spells.Spell : "> knows"


  entities.classes.CharacterClass "1"  o--> "-_startingEquipment" items.Equipment : "> has"
  entities.classes.CharacterClass "1"  *--> "-_bonusStat" entities.Statistics : "> has a bonus"
  entities.races.Race "1"  o--> "-_bonusStat" entities.Statistics : "> has a bonus"

  items.Equipment "1" *--> "-_bonusStat" entities.Statistics : "> has a bonus"


  Main "1"  o--> DM : "> starts the game"

 }

@enduml